### ISSUE TITLE
add "px" to "vw" mixin

### ISSUE THREAD

**Issue by kvidek** [degordian/sassbox#2]
mixin for converting px (PS, Sketch, Zeplin) to viewport width unit

```
//CONVERT px TO vw
@function get-vw($target) {
    $vw-context: (1440 * 0.01) * 1px;
    @return ($target / $vw-context) * 1vw;
}

**Comment by igorbumba** [comment]
1440 is some default value? That is artboard width from the design? Is that number subject to change?

**Comment by renatoruk** [comment]
Added in https://github.com/degordian/sassbox/commit/e1ddecbfdc4f48e53fb6f443ed9feed7ab046c62
