### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by igorbumba** [degordian/sassbox#6]
Add CONTRIBUTING.md from the: https://github.com/degordian/front/blob/master/labs/vue-teamwork-app/CONTRIBUTING.md

If something doesn't fit into our project, please do tell.

**Comment by renatoruk** [comment]
Added in https://github.com/degordian/sassbox/commit/27e10ec8c2a9c3fffa249c1e1fe1ce55f0f8d987
